
name: Build and Release macOS Binaries
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      prerelease:
        description: 'Mark as Pre-release?'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"
      - name: Build for x86_64
        run: swift build --arch x86_64 --configuration release
      - name: Build for ARM64
        run: swift build --arch arm64 --configuration release
      - name: Create Directories for Artifacts
        run: mkdir -p ./artifacts
      - name: Create universal binary
        run: lipo -create -output "dabadoo_universal" ".build/x86_64-apple-macosx/release/dabadoo" ".build/arm64-apple-macosx/release/dabadoo"
      - name: Copy universal binary
        run: cp dabadoo_universal ./artifacts/dabadoo
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/dabadoo"
          tag: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease == 'true' }}
          name: Release ${{ github.event.inputs.version }}
          token: ${{ secrets.RELEASE_TOKEN }}
